#!/usr/bin/env python3
"""Draw the base maps for "Your Agadir from Lynx" from OpenStreetMap data (stdlib only).

    python3 tools/mapdata.py

Inputs (gitignored, on disk): research/raw/_ovp_roads.json (trunk→tertiary roads +
coastline, Overpass 2026-10-02), _ovp_beachgeom.json (beach polygon), _ovp_g2.json
(Vallée des Oiseaux, Souk El Had, cable-car line), _ovp_geom.json (Rue El Mahdi Ibn
Toumert) and, when present, _ovp_near.json (small streets + parks around the hotel).
Outputs (committed): site/assets/img/map-city.svg, map-city-m.svg, map-door.svg
(geometry only, no text, © OpenStreetMap contributors / ODbL) and content/map.json
(projection of each map, read by tools/templates.py to place translated markers).
"""
import json, math, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "research", "raw")
PIN = (30.4228588, -9.5917027)

MAPS = {
    # Talborjt to the sea: hotel, gardens, museums, beach, marina, Souk El Had
    "city": {"lat": (30.4085, 30.4325), "lng": (-9.6185, -9.5745), "w": 1000, "eps": 1.1},
    # the same map framed for phones (shown below 48rem): Lynx to the sand and the marina, no sideways
    # scrolling; roads drawn heavier because it renders at ~345 px. Souk El Had and the taxi-only
    # places fall outside and are listed under it.
    "city-m": {"lat": (30.4060, 30.4305), "lng": (-9.6150, -9.5860), "w": 600, "eps": .9, "road_scale": 1.05},
    # Around the door: ±600 m
    "door": {"lat": (PIN[0] - 0.0050, PIN[0] + 0.0050), "lng": (PIN[1] - 0.0066, PIN[1] + 0.0066), "w": 600, "eps": .6},
}
ROAD_W = {"trunk": 7, "primary": 7, "secondary": 5, "tertiary": 3.4, "residential": 1.8,
          "unclassified": 1.8, "living_street": 1.6, "pedestrian": 2.2, "service": 1}
COL = {"land": "#e6d9d9", "sea": "#384770", "sand": "#f3e2c4", "park": "#d4d3c1", "road": "#fffdfc",
       "souk": "#d9c9c9", "street": "#15110f"}


def load(name):
    p = os.path.join(RAW, name)
    if not os.path.exists(p):
        return []
    try:
        return json.load(open(p))["elements"]
    except ValueError:
        return []


def proj(spec):
    lat0, lat1 = spec["lat"]
    lng0, lng1 = spec["lng"]
    c = math.cos(math.radians((lat0 + lat1) / 2))
    k = spec["w"] / ((lng1 - lng0) * c)
    h = round((lat1 - lat0) * k)
    return {"lng0": lng0, "lat1": lat1, "c": c, "k": k, "w": spec["w"], "h": h,
            "m": k / 111320}  # px per metre


def xy(p, lat, lng):
    return ((lng - p["lng0"]) * p["c"] * p["k"], (p["lat1"] - lat) * p["k"])


def rdp(pts, eps):
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    n = math.hypot(dx, dy) or 1e-9
    best, idx = 0, 0
    for i in range(1, len(pts) - 1):
        x, y = pts[i]
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / n
        if d > best:
            best, idx = d, i
    if best > eps:
        return rdp(pts[:idx + 1], eps)[:-1] + rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]


def inside(p, x, y, pad):
    return -pad <= x <= p["w"] + pad and -pad <= y <= p["h"] + pad


def path(p, geom, eps, closed=False, clip=True):
    """Projected, simplified SVG path; open lines are split where they leave the frame."""
    pts = [xy(p, g["lat"], g["lon"]) for g in geom]
    runs, cur = [], []
    for x, y in pts:
        if not clip or inside(p, x, y, 40):
            cur.append((x, y))
        elif cur:
            runs.append(cur); cur = []
    if cur:
        runs.append(cur)
    out = []
    for r in runs:
        r = rdp(r, eps)
        if len(r) < 2:
            continue
        out.append("M" + "L".join(f"{x:.1f} {y:.1f}".replace(".0 ", " ") for x, y in r) + ("Z" if closed else ""))
    return "".join(out)


def coast_chain(ways):
    """Stitch OSM coastline ways (land on the left) into one chain."""
    ways = [w["geometry"] for w in ways]
    key = lambda g: (round(g["lat"], 7), round(g["lon"], 7))
    by_start = {key(w[0]): w for w in ways}
    ends = {key(w[-1]) for w in ways}
    starts = [w for w in ways if key(w[0]) not in ends]
    chains = []
    for s in starts:
        ch, w = list(s), s
        while key(w[-1]) in by_start and len(ch) < 100000:
            w = by_start.pop(key(w[-1]))
            ch += w[1:]
        chains.append(ch)
    return max(chains, key=len) if chains else []


def build(name, spec, roads, coast, beach, polys, street):
    p = proj(spec)
    W, H, eps = p["w"], p["h"], spec["eps"]
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}">',
             f'<!-- © OpenStreetMap contributors, ODbL. Generated by tools/mapdata.py -->',
             f'<rect width="{W}" height="{H}" fill="{COL["land"]}"/>']
    # sea: coastline chain (sea on its right = west) closed round the far west/south
    if coast:
        pts = [xy(p, g["lat"], g["lon"]) for g in coast]
        pts = rdp(pts, eps)
        x_end, y_end = pts[-1]
        x_st, y_st = pts[0]
        far = -4000
        ring = pts + [(x_end, 9000), (far, 9000), (far, -9000), (x_st, -9000)]
        parts.append(f'<path fill="{COL["sea"]}" d="M' + "L".join(f"{x:.1f} {y:.1f}" for x, y in ring) + 'Z"/>')
    for g, col in polys:
        parts.append(f'<path fill="{col}" d="{path(p, g, eps, closed=True, clip=False)}"/>')
    if beach:
        parts.append(f'<path fill="{COL["sand"]}" d="{path(p, beach, eps, closed=True, clip=False)}"/>')
    # roads, minor first
    order = ["service", "living_street", "unclassified", "residential", "pedestrian", "tertiary", "secondary", "primary", "trunk"]
    scale = spec.get("road_scale", W / 1000)
    for cls in order:
        d = "".join(path(p, w["geometry"], eps) for w in roads if w["tags"].get("highway") == cls)
        if d:
            sw = max(ROAD_W[cls] * (1.6 if name == "door" else 1) * scale, .8)
            parts.append(f'<path fill="none" stroke="{COL["road"]}" stroke-width="{sw:.1f}" stroke-linecap="round" stroke-linejoin="round" d="{d}"/>')
    if street:
        sw = 3.4 if name == "door" else 2.6 * scale
        parts.append(f'<path fill="none" stroke="{COL["street"]}" stroke-width="{max(sw, 2.2):.1f}" stroke-linecap="round" d="{path(p, street, eps)}"/>')
    parts.append("</svg>")
    svg = "\n".join(parts) + "\n"
    out = os.path.join(ROOT, "site", "assets", "img", f"map-{name}.svg")
    with open(out, "w") as f:
        f.write(svg)
    print(f"map-{name}.svg {len(svg) // 1024} KB, {W}x{H}")
    return {k: (round(v, 6) if isinstance(v, float) else v) for k, v in p.items()}


def main():
    roads_raw = load("_ovp_roads.json")
    roads = [e for e in roads_raw if "highway" in e.get("tags", {}) and e.get("geometry")]
    coast = coast_chain([e for e in roads_raw if e.get("tags", {}).get("natural") == "coastline"])
    beach = next((e["geometry"] for e in load("_ovp_beachgeom.json") if e["type"] == "way"), None)
    g2 = {e["id"]: e for e in load("_ovp_g2.json")}
    near = load("_ovp_near.json")
    parks = [e["geometry"] for e in near if e.get("tags", {}).get("leisure") and e.get("geometry")]
    if 50192615 in g2:
        parks.append(g2[50192615]["geometry"])          # Vallée des Oiseaux
    polys = [(g, COL["park"]) for g in parks]
    if 362660313 in g2:
        polys.append((g2[362660313]["geometry"], COL["souk"]))  # Souk El Had
    street = next((e["geometry"] for e in load("_ovp_geom.json") if e["type"] == "way"), None)
    minor = [e for e in near if "highway" in e.get("tags", {}) and e.get("geometry")]
    out = {"_note": "Projection of site/assets/img/map-*.svg (tools/mapdata.py). x = (lng-lng0)*c*k, y = (lat1-lat)*k; m = px per metre.",
           "pin": list(PIN)}
    for name, spec in MAPS.items():
        out[name] = build(name, spec, roads + (minor if name == "door" else []), coast, beach, polys, street)
    with open(os.path.join(ROOT, "content", "map.json"), "w") as f:
        json.dump(out, f, indent=1)
    print("content/map.json")


if __name__ == "__main__":
    main()
